spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true      -> System.out
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10 #기본 page 사이즈(Web 확장)
        max-page-size: 2000 #최대 page 사이즈(Web 확장)

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace      # 파라미터까지 볼 수 있음